import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>
          Create Next App
        </title>
        <meta name="description" content="Generated by create next app"/>
      </Head>
      <h1 className='text-3xl font-bold'>Next Eshop</h1>
    </div>
  )
}
